Models/ErrorViewModel.cs
namespace Agriculture.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Agriculture.Controllers
{
    public class EquipmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FarmCropController.cs
using Microsoft.AspNetCore.Mvc;
using Agriculture.Models;

namespace Agriculture.Controllers
{
    public class FarmCropController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Agriculture.Models;

namespace Agriculture.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LivestockController.cs
using Microsoft.AspNetCore.Mvc;
using Agriculture.Models;

namespace Agriculture.Controllers
{
    public class LivestockController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TechnologyController.cs
using Microsoft.AspNetCore.Mvc;
using Agriculture.Models;

namespace Agriculture.Controllers
{
    public class TechnologyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Equipment/Index.cshtml
<div class="container">
    <img src="~/images/equip.png" alt="equipment" class="d-block w-100 img-responsive" />
    <hr />
    <div class="row">
        <center>
            <h1>
                - OUR PRODUCTS -
            </h1>
        </center>
    </div>
    <hr />
    <br />
    <!--first row-->
    <div class="row">
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Tractors</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/fendt1.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--https://www.fendt.com/us/tractors/700-vario-my-2020-highlights-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Combines</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/fendtcombine.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--ideal 10t-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Front-End Loaders</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/frontcat.jpg" alt="machinery" class="d-block w-100 img-responsive" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Augers</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/auger.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--https://www.agweb.com/article/kinze-expands-grain-cart-line-develops-planter-prototype-NAA-katie-humphreys-->
            </div>
        </div>
    </div>

    <!--Second row-->
    <div class="row" id="rowSpacing">
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Cultivators</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/Cultivator.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--https://www.ongmac.com.au/product/new-equipment/agricultural-equipment/attachments-and-machinery/farm-implements/farm-implements-cultivators-harrows/s-tine-cultivator/-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Plows</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/plow.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--Kuhn Multi Master 123 4 - NSH-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Sprayers</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/sprayer.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--Kuhn Metris 4100 sprayer-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Planters</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/planter.jpg" alt="machinery" class="d-block w-100 img-responsive" />
            </div>
        </div>
    </div>

    <!--Third row-->
    <div class="row">
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Mowers</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/fendtmower.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--2021 FENDT CUTTER 310TL-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Rakes</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/rotaryrake.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--https://www.agriculture-xprt.com/downloads/dragonfly-model-7700-double-rotary-rake-brochure-680433-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Balers</h3>
                </center>
            </div>
            <div class="cardBox">
               <img src="~/images/baler.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--kuhn baler-->
            </div>
        </div>
        <div class="col-md-3">
            <div class="cardText">
                <center>
                    <h3>Manure Spreaders</h3>
                </center>
            </div>
            <div class="cardBox">
                <img src="~/images/manure.jpg" alt="machinery" class="d-block w-100 img-responsive" />
                    <!--2021 KUHN KNIGHT PS150-->
            </div>
        </div>
    </div>
     <br />
     <hr />
    <div class="row">
        <center>
            <h1>
                - FOR MORE PRODUCTS CONTACT US-
            </h1>
        </center>
    </div>

Views/FarmCrop/Index.cshtml
<div class="container">
    <img src="~/images/combine.png" alt="equipment" class="d-block w-100 img-responsive" />
    <hr /><div class="row">
        <center>
            <h1>
                - OUR CROPS -
            </h1>
        </center>
    </div>
    <hr />
</div>

<br />

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card">
                <img src="~/images/wheat.jpg" class="card-img-top" alt="wheat">
                <div class="card-body">
                    <h5 class="card-title">WHEAT</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Rolls, bread, baked goods</li>
                    <li class="list-group-item">Cookies, cakes</li>
                    <li class="list-group-item">Pasta and noodles</li>
                    <li class="list-group-item">Wheat beer</li>
                    <li class="list-group-item">Packaged convenience foods, soups, sauces</li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="~/images/barley.jpg" class="card-img-top" alt="barley">
                <div class="card-body">
                    <h5 class="card-title">BARLEY</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Hulled or whole-grain barley</li>
                    <li class="list-group-item">Flour</li>
                    <li class="list-group-item">Flakes</li>
                    <li class="list-group-item">Grits</li>
                    <li class="list-group-item">Malt</li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="~/images/canola.jpg" class="card-img-top" alt="canola">
                <div class="card-body">
                    <h5 class="card-title">CANOLA</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Oil</li>
                    <li class="list-group-item">Canola Meal(Livestock Feed)</li>
                    <li class="list-group-item">Fried snack foods</li>
                    <li class="list-group-item">Breads</li>
                    <li class="list-group-item">Cookies</li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="~/images/Corn.jpg" class="card-img-top" alt="corn">
                <div class="card-body">
                    <h5 class="card-title">CORN</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Cornstarch</li>
                    <li class="list-group-item">Flour</li>
                    <li class="list-group-item">Peanut butter</li>
                    <li class="list-group-item">Corn syrup</li>
                    <li class="list-group-item">Bakery products</li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="~/images/soy.jpg" class="card-img-top" alt="soybean">
                <div class="card-body">
                    <h5 class="card-title">SOYBEAN</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Soymilk</li>
                    <li class="list-group-item">Soy sauce</li>
                    <li class="list-group-item">Oil</li>
                    <li class="list-group-item">Salad dressings</li>
                    <li class="list-group-item">Mayonnaises</li>
                </ul>
            </div>
        </div>
    </div>

</div>

Views/Home/About.cshtml
<div class="container">
    <div class="row">
        <img src="~/images/machinery.jpg" alt="multibanner" class="d-block w-100 img-responsive" />
    </div>
    <br /><hr />
    <center><h1>- OUR MISSION -</h1></center><hr />
    <p>
        <center>
            <b>
                <i>
                    To work together in agricultural community and provide eco-friendly solutions!!
                </i>
            </b>
        </center>
    </p>
    <br /><hr />
    <center><h1>- ABOUT US -</h1></center><hr />
    <div class="row">
        <div class="col-md-6">
            <br /><br />
            <p>
                Agriculture supports other businesses in the farming community. Our company provides services that
                specialize in agricultural digital technologies that can provide eco friendly solutions.
            </p>
        </div>
        <div class="col-md-6">
            <img src="~/images/globe1.jpg" alt="" class="d-block w-100 img-responsive" />
        </div>
    </div>
</div>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<h1>@ViewData["Title"]</h1>
<br/>
<div>
    <div class="row">
         <div class="col">
            <address>
                One Microsoft Way<br />
                Redmond, WA 98052-6399<br />
                <abbr>Phone:</abbr>
                425.555.0100
            </address>

            <address>
                <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
            </address>
        </div>
         <div class="col">
             <img src="~/images/contact.jpg" />
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/tractor1.jpg" class="d-block w-100" alt="agribanner">
            <div class="carousel-caption d-none d-md-block">
                <p>Sign Up To Our Newsletter</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/multibanner.jpg" class="d-block w-100" alt="multibanner">
            <div class="carousel-caption d-none d-md-block"></div>
        </div>
        <div class="carousel-item">
            <img src="~/images/combine1.jpg" class="d-block w-100" alt="combine">
            <div class="carousel-caption d-none d-md-block">
                <p>Learn More How Farmers Across The Nation Build A Better Community</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="container" style="margin-top:25px;">
    <div class="row row-cols-1 row-cols-md-4 g-4">
        <div class="col">
            <div class="card">
                <a href="@Url.Action("Index","Technology")">
                    <img src="~/images/agtech.png" class="card-img-top" alt="technology">
                </a>
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Technology </h5>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <a href="@Url.Action("Index","Equipment")">
                    <img src="~/images/agmachine.jpg" class="card-img-top" alt="equipment">
                </a>
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Equipment</h5>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <a href="@Url.Action("Index","Livestock")">
                    <img src="~/images/livestock.jpg" class="card-img-top" alt="livestock">
                </a>
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Livestock</h5>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <a href="@Url.Action("Index","FarmCrop")">
                    <img src="~/images/income1.jpg" class="card-img-top" alt="crop">
                </a>
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Farm Crops</h5>
                </div>
            </div>
        </div>
    </div>

</div>

        <hr />

        <div class="row">
            <center>
                <h1>
                    - OUR SPONSORS -
                </h1>
            </center>
        </div>
        <hr />

        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href="https://www.kuhn.com/internet/kuhncom.nsf/pakuhncom.htm" target="_blank">
                        <img src="~/images/kuhn.png" alt="kuhn" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.caterpillar.com/" target="_blank">
                        <img src="~/images/cat.png" alt="cat" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.newholland.com/Pages/splash.html" target="_blank">
                        <img src="~/images/holland1.jpg" alt="newholland" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.bobcat.com/index" target="_blank">
                        <img src="~/images/bobcat.png" alt="bobcat" class="d-block w-100 img-responsive" />
                    </a>
                </div>
            </div>
            <br /><br />
            <div class="row">
                <div class="col-md-3">
                    <a href="https://www.agcocorp.com/" target="_blank">
                        <img src="~/images/agco.png" alt="agco" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.fendt.com/int/index" target="_blank">
                        <img src="~/images/FendtLogo.png" alt="fendt" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.valtra.com/" target="_blank">
                        <img src="~/images/Valtra.png" alt="valtra" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.deere.com/en/index.html" target="_blank">
                        <img src="~/images/jd2.jpg" alt="johndeere" class="d-block w-100 img-responsive" />
                    </a>
                </div>
            </div>
            <br /><br />
            <div class="row">
                <div class="col-md-3">
                    <a href="https://www.masseyferguson.com/en_us.html" target="_blank">
                        <img src="~/images/massey.jpg" alt="massey" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.krone-northamerica.com/" target="_blank">
                        <img src="~/images/krone.png" alt="krone" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.cnhindustrial.com/en-us/Pages/homepage.aspx" target="_blank">
                        <img src="~/images/cnh.jpg" alt="cnh" class="d-block w-100 img-responsive" />
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="https://www.zetorna.com/?redirect" target="_blank">
                        <img src="~/images/zetor.png" alt="zetor" class="d-block w-100 img-responsive" />
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">

            </div>

            <div class="col-md-6">

            </div>
        </div>

Views/Livestock/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container">
    <img src="~/images/animalGroup.png" alt="animalGroup" class="d-block w-100 img-responsive" />
    <hr /><div class="row">
        <center>
            <h1>
                - OUR ANIMALS -
            </h1>
        </center>
    </div>
</div>
<hr />
<br />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="~/images/cows.jpg" alt="cows" class="d-block w-100 img-responsive" />
        </div>

        <div class="col-md-6">
            <center><h4>Guide To Feed Cattle</h4></center>
            <button type="button" class="collapsible">Determine how much food your cattle needs</button>
            <div class="content">
                <p>
                    <b>Diary Cattle </b>require more feed to maintain their weight than beef cattle<br />
                    <b>British breeds (Angus,Shorthorn, or Hereford) </b>have lower food needs<br />
                    <b>Continental breeds (Charolais or Limousin) </b>typically need more energy and protein<br />
                    <b>Exotic breeds </b> have higher feed requirements than continental or British breeds<br />
                </p>
            </div>
            <button type="button" class="collapsible">Figure out how much weight you cattle should gain</button>
            <div class="content">
                <p>
                    Average Daily Gain (ADG) is determined by your cattle’s current weight, their body fat composition,
                    and their age. Take the target weight of your cow and subtract its current weight. Then divide that
                    number by how many days until you want the cow to reach its target weight.
                </p>
            </div>
            <button type="button" class="collapsible">Feed cattle based on weather and location</button>
            <div class="content">
                <p>
                    <b>Increase food</b><br />
                    <ul>
                        <li>Temps drops below -4 F (-20 C)</li>
                        <li>High winds in the area</li>
                    </ul>
                    <b>Decrease food</b><br />
                    <ul>
                        <li>Temps goes above 86 F (30 C)</li>
                        <li>Nights colling does not occur</li>
                    </ul>
                </p>
            </div>
            <button type="button" class="collapsible">Common high-quality feed that meets the nutrutional requirements</button>
            <div class="content">
                <p>
                    <ul>
                        <li>Hay</li>
                        <li>Grain (Oats, Wheat, Barley, Rye)</li>
                        <li>Straw or chaff</li>
                        <li>Vitamin or mineral supplements</li>
                        <li>Salt</li>
                    </ul>
                </p>
            </div>
            <button type="button" class="collapsible">Determine what feeds are available</button>
            <div class="content">
                <p>
                    <b>Mix </b>A combination of hay, silage, grain, supplement, mineral, salt, by-product, salt, vitamin, etc.e<br />
                    <b>Hay </b>A grass, legume, or grass-legume mix. Pasture available for grazing may be also included in this feed type,
                    even though pasture isn't sun-cured harvested forage like hay is<br />
                    <b>Grain </b>Includes corn, oats, barley, wheat, rye, and triticale<br />
                    <b>Straw/Chaff</b>Typically includes cereal grain chaff baled, barley, oats, triticale, rye, and wheat.
                    Legume or pulse straw also includes pea, flax, lentil, and greenfeed<br />
                    <b>Vitamins </b>Vitamins A, D, and E are sold in various forms as a feed-mix supplement<br />
                    <b>Minerals </b>Are calcium [Ca], phosphorus [P], sodium [Na], chloride [Cl], potassium [K], magnesium [Mg], and sulphur [S].
                    Microminerals are cobalt [Co], iodine [I], iron [Fe], molybdenum [Mo], manganese [Mn], copper [Cu], zinc [Zn], and selenium [Se].
                    Mineral bags with Ca and P are usually sold as a ratio of 1:1 or 2:1. Less common are mineral sold as greater than 2:1,
                    though 7:1 is still appropriate for cattle. Macrominerals are labelled as a percentage while microminerals are labelled as mg/kg
                    or parts per million [ppm]<br />
                    <b>Salt </b>Comes in block or loose form. Most blocks are 95 to 98% salt and 5% or 2% mineral respectively`<br />
                </p>
            </div>
            <script>var coll = document.getElementsByClassName("collapsible");
                var i;

                for (i = 0; i < coll.length; i++) {
                    coll[i].addEventListener("click", function () {
                        this.classList.toggle("active");
                        var content = this.nextElementSibling;
                        if (content.style.display === "block") {
                            content.style.display = "none";
                        } else {
                            content.style.display = "block";
                        }
                    });
                }</script>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <img src="~/images/pigs.jpg" alt="pigs" class="d-block w-100 img-responsive" />
        </div>

        <div class="col-md-6">
            <center><h4>Guide To Feed Pigs</h4></center>
            <div>
                <ul>
                    <li>A combination of protein source, milk replacer, vitamins, amino acids and rich feed ingredients makes this complete feed the ideal start for young healthy piglets.</li>
                    <li>Feeds should meet the animal’s needs for maintenance, growth and reproduction. Good pig feed contains sufficient energy, protein, minerals and vitamins. Rice bran, broken rice, maize, soya-beans, cassava, vegetables and distillers’ residues are often used in pig feed.</li>
                    <li>
                        Pigs must also be fed on time, since it makes them familiar to the feeding regime. Pigs need to be fed according to their sizes and ages. Troughs must be anchored so they cannot be turned over.
                    </li>
                    <li>By not providing enough water for your pigs you will reduce their daily feed intake. Ample clean water must be available for your pigs to drink at all times.</li>
                </ul>
            </div>
        </div>
    </div>
    <br /><br />
          <div class="row">
              <div class="col-md-6">
                  <img src="~/images/chickens.jpg" alt="chickens" class="d-block w-100 img-responsive" />
              </div>
              <div class="col-md-6">
                  <p>
                      <center><h4 style="bottom: 5px; position: relative;">Guide To Raise Chickens</h4></center>
                  </p>

                  <table class="tableStyle" style=" bottom:10px; position:relative;">
                      <thead>
                          <tr class="tableColor">
                              <th>Prepare Their Home</th>
                              <th>Choose Your Chickens</th>
                              <th>Start Farming</th>
                          </tr>
                      </thead>
                      <tr>
                          <td>Make sure you're got the space</td>
                          <td>Go for pullets</td>
                          <td>Feed them</td>
                      </tr>
                      <tr>
                          <td>Choose a coop</td>
                          <td>Pick a breed</td>
                          <td>Let them roam</td>
                      </tr>
                      <tr>
                          <td>Buy a drinker and a feeder</td>
                          <td>Spring for a trio</td>
                          <td>Harvest you breakfast daily</td>
                      </tr>
                      <tr>
                          <td>Give their feet a break</td>
                          <td>Hens only</td>
                          <td>Clean up and compost</td>
                      </tr>
                  </table>
              </div>

          </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <img src="~/images/sheep.jpg" alt="sheep" class="d-block w-100 img-responsive" />
        </div>

        <div class="col-md-6">
            <center><h4>Guide To Breed Sheep</h4></center>
            <div>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/dr9_FuYGAsA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <img src="~/images/horses.jpg" alt="horses" class="d-block w-100 img-responsive" />
        </div>

        <div class="col-md-6">
            <center><h4>Guide To Take Care Of Horses</h4></center>
            <div>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/zI8JSTGtRQc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>